export const enum URLS {
  TYPESCRIPT = "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/typescript/typescript-original.svg",
  JAVASCRIPT = "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/javascript/javascript-original.svg",
  PYTHON = "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/python/python-original.svg",
  CPP = "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/cplusplus/cplusplus-original.svg",
  C = "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/c/c-original.svg",
  REACT = "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/react/react-original.svg",
  NODE = "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nodejs/nodejs-original.svg",
  REDUX = "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/redux/redux-original.svg",
  FASTAPI = "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/fastapi/fastapi-original.svg",
  DOCKER = "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/docker/docker-original.svg",
  CSS3 = "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/css3/css3-plain.svg",
  HTML5 = "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/html5/html5-plain.svg",
  POSTGRESQL = "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/postgresql/postgresql-plain.svg",
  GIT = "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/git/git-original.svg",
}

export const enum DESCRIPTIONS {
  TYPESCRIPT = "TypeScript",
  JAVASCRIPT = "JavaScript",
  PYTHON = "Python",
  CPP = "C++",
  C = "C",
  REACT = "React",
  NODE = "Node",
  REDUX = "Redux",
  FASTAPI = "FastAPI",
  DOCKER = "Docker",
  CSS3 = "CSS3",
  HTML5 = "HTML5",
  POSTGRESQL = "PostgreSQL",
  GIT = "Git",
}
